name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # main 브랜치에 Push될 때 실행

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 현재 GitHub 코드 가져오기

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ybigta_newbie_team_project:latest

  deploy-to-ec2:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa || (echo "Failed to add SSH key" && cat ~/.ssh/id_rsa && exit 1)
          ssh-keyscan -t rsa ${SSH_HOST} >> ~/.ssh/known_hosts

      - name: Debug SSH Key (safely)
        run: |
          echo "First few lines of SSH key (safely):"
          head -n 1 ~/.ssh/id_rsa
          echo "File permissions:"
          ls -l ~/.ssh/id_rsa
          echo "Key format check:"
          ssh-keygen -l -f ~/.ssh/id_rsa || echo "Invalid key format"

      - name: Deploy to EC2
        env:
          SSH_HOST: ${{ secrets.EC2_HOST }}
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${SSH_HOST} << 'EOF'
            sudo docker stop my-container || true
            sudo docker rm my-container || true
            sudo docker pull ${DOCKER_USER}/ybigta_newbie_team_project:latest
            sudo docker run -d -p 8000:8000 --name my-container ${DOCKER_USER}/ybigta_newbie_team_project:latest
          EOF