name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # main 브랜치에 Push될 때 실행

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 현재 GitHub 코드 가져오기

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ybigta_newbie_team_project:latest

  deploy-to-ec2:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: |
            ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo docker stop my-container || true
            sudo docker rm my-container || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/ybigta_newbie_team_project:latest
            sudo docker run -d -p 8000:8000 --name my-container ${{ secrets.DOCKER_USERNAME }}/ybigta_newbie_team_project:latest